name: BDM-DataLake-Terraform-Deploy-Prod
run-name: Release ${{ github.ref_name }}

on:
  workflow_dispatch:

  push:
    tags:
      - '[0-9].[0-9].[0-9][0-9][0-9][0-9]'

jobs:
    datalake-terraform-plan-preprod:
      environment: PREPROD
      runs-on: ubuntu-latest
      if: ${{ !contains(github.ref_name, 'nonprod' ) }}
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/preprod-backend-config.tfvars -no-color -input=false

      - name: Terraform plan
        working-directory: ${{ github.workspace }}
        run: |
          terraform plan -var-file=var-overrides/preprod.tfvars -no-color -input=false -out=./tfplan | tee ./terraform-plan-output.txt

    datalake-terraform-apply-preprod:
      environment: PREPROD
      runs-on: ubuntu-latest
      needs: datalake-terraform-plan-preprod
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/preprod-backend-config.tfvars -no-color -input=false

      - name: Terraform apply
        working-directory: ${{ github.workspace }}
        run: |
          terraform apply -var-file=var-overrides/preprod.tfvars -input=false -no-color -auto-approve

    datalake-terraform-plan-prod:
      environment: PROD
      runs-on: ubuntu-latest
      if: ${{ !contains(github.ref_name, 'nonprod') }}
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/prod-backend-config.tfvars -no-color -input=false

      - name: Terraform plan
        working-directory: ${{ github.workspace }}
        run: |
          terraform plan -no-color -var-file=var-overrides/prod.tfvars -input=false -out=./tfplan | tee ./terraform-plan-output.txt

    datalake-terraform-apply-prod:
      environment: PROD
      runs-on: ubuntu-latest
      needs: datalake-terraform-plan-prod
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/prod-backend-config.tfvars -no-color -input=false

      - name: Terraform apply
        working-directory: ${{ github.workspace }}
        run: |
          terraform apply -var-file=var-overrides/prod.tfvars -input=false -no-color -auto-approve
