name: BDM-DataLake-Terraform-Deploy-Nonprod
run-name: Release ${{ github.ref_name }}

on:
  workflow_dispatch:

  push:
    tags:
      - '[0-9].[0-9].[0-2000]-nonprod'

jobs:
    datalake-terraform-plan-dev:
      environment: DEV
      runs-on: ubuntu-latest
      if: ${{ contains(github.ref_name, 'nonprod' ) }}
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install Infisical
        working-directory: ${{ github.workspace }}
        run: |
          apt-get update && curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical
          infisical --version

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/dev-backend-config.tfvars -no-color -input=false

      - name: Terraform plan
        working-directory: ${{ github.workspace }}
        run: |
          terraform plan -var-file=var-overrides/dev.tfvars -no-color -input=false -out=./tfplan | tee ./terraform-plan-output.txt

    datalake-terraform-apply-dev:
      environment: DEV
      runs-on: ubuntu-latest
      needs: datalake-terraform-plan-dev
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/dev-backend-config.tfvars -no-color -input=false

      - name: Terraform apply
        working-directory: ${{ github.workspace }}
        run: |
          terraform apply -var-file=var-overrides/dev.tfvars -input=false -no-color -auto-approve

    datalake-terraform-plan-sit:
      environment: SIT
      runs-on: ubuntu-latest
      if: ${{ contains(github.ref_name, 'nonprod' ) }}
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/sit-backend-config.tfvars -no-color -input=false

      - name: Terraform plan
        working-directory: ${{ github.workspace }}
        run: |
          terraform plan -no-color -var-file=var-overrides/sit.tfvars -input=false -out=./tfplan | tee ./terraform-plan-output.txt

    datalake-terraform-apply-sit:
      environment: SIT
      runs-on: ubuntu-latest
      needs: datalake-terraform-plan-sit
      defaults:
        run:
          shell: bash
      outputs:
        tag: ${{ steps.tags.outputs.new_tag }}
      steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: ${{ github.workspace }}
        run: |
          terraform init -backend-config BackendConfig/sit-backend-config.tfvars -no-color -input=false

      - name: Terraform apply
        working-directory: ${{ github.workspace }}
        run: |
          terraform apply -var-file=var-overrides/sit.tfvars -input=false -no-color -auto-approve
