name: Zal-Test-Workflow

on:
  push:
    tag: '[0-9].[0-9].[0-9].[0-9]'

run-name: Deploying Release ${{ github.ref }}

jobs:
    datalake-terraform-deploy-dev:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.release_version }}

      - name: Confirm Release Checked out successfully
        run: |
          ls -la .github