name: Zal-Test-Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string

run-name: Deploying Release ${{ inputs.release_version }}

jobs:
    datalake-terraform-deploy-dev:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.release_version }}

      - name: Confirm Release Checked out successfully
        run: |
          ls -la .github